### ISSUE TITLE
Better logger

### ISSUE THREAD

**Issue by CatCode79** [Davidster/ikari#15]
While the logger is improving a lot. In my opinion, some doubts and potential improvements remain.

What immediately caught my eye the first time I took a look at the project was that there was a dedicated logger instead of using env_logger (which we already have as a dependency).
In fact, unless I missed something, I think we can do without it and use env_logger instead.

What I would do is:
- remove the pure logging part inside the logger.rs and use log::info! in its place
- probably the console crate dependency shouldn't be needed anymore either
- change the name from logger to frametime

If there was a performance issue and you needed to create a buffer that sends bits of output bit by bit (like in c/c++) instead of all at once (like in rust) it seems to me that there are ways to fix it (remember that I had read something about it).

It's really well done, you have the option to compile or not the various logging levels (they are macros) and even the compiled ones can be activated via an environment variable.
The only flaw I found is the impossibility of adding custom log levels: you have to use filter and regex in which case you don't want some types of messages.

If we really need our own type of logger we can use the generic interface of the log crate and [use a patch](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html) in the cargo.toml to force the use of our logger instead of all the env_logger crates in the cargo tree (this is to be fussy about dependencies, actually env_logger doesn't weigh much in the compilation..).

Not strictly related:
In the rustlang std they are adding once_cell (see: Tracking Issue for once_cell #74465) which is basically the lazy_static crate. If you look at the first example of the once_cell crate it is really related to a logger: https://docs.rs/once_cell/latest/once_cell/
All this to say that it is not a problem to add a dependency now, in case you want to keep the lazy_static solution, this because sooner or later it would be changed to the once_cell solution of the rust language.

**Comment by Davidster** [comment]
the two reasons I implemented my own logger were 1) I didn't want to spend time learning how env_logger worked and 2) for the Term::clear_screen function, so the fps is pinned to the top of the terminal and updates in realtime meanwhile the rest of the logs stay there until more logs come in. the reason env_logger is there as a dependency is just grandfathered in from the [learnwgpu tutorials](https://sotrh.github.io/learn-wgpu/).

do you think there would be a way to set up env_logger so that it behaves in a similar way to right now?

another thing to note is that the FPS counter could theoretically be moved into an overlay via an egui integration (or equivalent), removing the need for the clear_screen function

**Comment by Davidster** [comment]
> In the rustlang std they are adding once_cell

very cool! nice to know we won't need lazy_static forever. How do you keep so up to date with the latest rust news? I get some notifications from /r/rust but that's about it. Is there some kind of newsletter?

**Comment by CatCode79** [comment]
> another thing to note is that the FPS counter could theoretically be moved into an overlay via an egui integration (or equivalent), removing the need for the clear_screen function

I think this solution might be the best because this way you can have all the information in the same window.
Once we have a gui integration (or maybe we can simply use wgpu_glyph) the logger should no longer be needed and we can standardize everything with env_logger, at least I'll explain better how its configuration works (in fact the documentation is a bit incomplete about).

On the choice of the gui I will open a discussion, there are some things to evaluate before making a choice.

**Comment by CatCode79** [comment]
> How do you keep so up to date with the latest rust news? I get some notifications from /r/rust but that's about it. Is there some kind of newsletter?

The official newsletter, full of links to interesting articles:
https://this-week-in-rust.org/

In the rust forum, you can get a weekly digest of the most read posts:
https://users.rust-lang.org/

I follow various discord servers, this one is a must link:
https://discord.com/invite/yNtPTb2

Others:
https://www.youtube.com/@RustGameDevelopment
https://gamedev.rs/news/025/

**Comment by CatCode79** [comment]
> do you think there would be a way to set up env_logger so that it behaves in a similar way to the current custom logger?

I was in a bit of a rush the other day and didn't answer this. I think the only way is to fork env_logger and modify it however we want, it's not particularly difficult but not exactly the best thing to do.

I realized I didn't explain well why I'd rather not have this dual logging system. If we want to create a rendering library this potentially can be used by other people who probably expect some kind of interfacing with the crate log. Giving two logging systems that behave differently can lead to confusion because the logger cannot be deactivated like the various env_logger channels.

Alternatively I think it's possible to mimic log deactivation (via features and via environment variable), at which point everything would be consistent with the behavior of crate log + env_logger.
I don't think it's worth it, it's more interesting to create a debug overlay where you put all the information in the same game window.

It should be noted that the current lazy_static + Mutex implementation (I think) has the advantage of sending sorted output to stdout (possibly with the disadvantage of having a small overhead?). However apart from this advantage it is generally not a drama to have it slightly messy, it is more important that it is there.
