### ISSUE TITLE
Incorrect spelling for warning in texture compressor

### ISSUE THREAD

**Issue by WinterAlexander** [Davidster/ikari#154]
https://github.com/Davidster/ikari/blob/master/clikari/src/texture_compressor.rs#L153

This should be fixed ASAP! Completely unusable

**Comment by Davidster** [comment]
Workin on it

**Comment by Davidster** [comment]
fixed in af2c596c7c4ca1ae07ea10adda5f3bb3e8f3e37a

**Comment by WinterAlexander** [comment]
Not fixed

**Comment by Davidster** [comment]
Damn, could you point me to which line is incorrect?

**Comment by WinterAlexander** [comment]
Already did in the description + the one you made wrong with your last commit

**Comment by Davidster** [comment]
Ok Devin

**Comment by Davidster** [comment]
closing stale issue
