### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by Davidster** [Davidster/ikari#19]
I want to rename it, and just replace all occurences from wgpu-sandbox -> ikari.

**Comment by CatCode79** [comment]
Do we also rename the github project with ikari instead of wgpu-sandobx? Even if someone saved the link to wgpu-sandox github handles the redirect

**Comment by Davidster** [comment]
yup, since the redirect is handled we should rename the github project imo

**Comment by CatCode79** [comment]
Okay! You have to rename it because I don't have access to the repo settings

**Comment by Davidster** [comment]
oh yeah definitely, I would feel bad to take your time for such a boring task 😃

**Comment by CatCode79** [comment]
The [#25](https://github.com/Davidster/ikari/pull/25) #[26](https://github.com/Davidster/ikari/pull/26) and [#27](https://github.com/Davidster/ikari/pull/27) PRs should have completed the renaming (+ window's title), I consider the issue as complete and close it.
