### ISSUE TITLE
better tracy profiling

### ISSUE THREAD

**Issue by CatCode79** [Davidster/ikari#21]
Because I got confused with the various crates that support tracy and I was convinced that profiling (which I chose because it is also used by wgpu) also supports profiling for memory allocation (which is done [here](https://github.com/SparkyPotato/tracy_full) instead).
If needed, I think we will still be able to use tracy_full crate together with profiling or we will implement it ourselves.

I recall seeing a tool that showed raw gpu traffic, not sure if tracy supports that, yet to investigate. Keep in mind this crate: https://github.com/wumpf/wgpu-profiler

**Comment by Davidster** [comment]
having memory tracking would be awesome! I'm very curious to know what the application's memory usage looks like

**Comment by CatCode79** [comment]
closed as completed by [#PR52](https://github.com/Davidster/ikari/pull/52)
