### ISSUE TITLE
glTF: make the NormalTangentTest work

### ISSUE THREAD

**Issue by Davidster** [Davidster/ikari#44]
see https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/NormalTangentTest/README.md

**Comment by CatCode79** [comment]
I think this can help you, it's one of the few bevy crates that can be used independently of the engine:
https://github.com/bevyengine/bevy/tree/main/crates/bevy_mikktspace

**Comment by Davidster** [comment]
@CatCode79 I ended up fixing this with bevy_mikktspace lol.. 1 year later. thanks again!
