### ISSUE TITLE
Switch to Symphonia for audio due to security advisory

### ISSUE THREAD

**Issue by Davidster** [Davidster/ikari#60]
Security advisory: https://github.com/Davidster/ikari/security/dependabot/3
Probably won't be fixed by minimp3 any time soon: https://github.com/germangb/minimp3-rs/pull/38
Alternative library which is more actively maintained: https://github.com/pdeljanov/Symphonia
Someone else also switching to Symphonia: https://github.com/RustAudio/rodio/issues/456#issuecomment-1327959956

**Comment by CatCode79** [comment]
I don't know Symphonia to tell the pros and cons, but [kira](https://crates.io/crates/kira) is a good alternative

**Comment by Davidster** [comment]
interestingly it seems like kira is using symphonia under the hood: https://github.com/tesselode/kira/blob/main/crates/kira/Cargo.toml.

seems like kira doesn't support 3d audio so I'd rather stick with oddio for the time being
