### ISSUE TITLE
MouseGrab on window with RAlt

### ISSUE THREAD

**Issue by CatCode79** [Davidster/ikari#63]
I noticed that in order to move the camera you have to press the RAlt key, which I think is quite counterintuitive for many.
I think it's better to use a "standard" that I've noticed in many games: left mouse click to grab the game view, Esc or Tab to exit that mode and have the mouse free to click on the UI

**Comment by Davidster** [comment]
definitely agree! I was thinking about this last night. currently the escape key exits the game but it can be used to pop up a UI with an exit button instead

**Comment by CatCode79** [comment]
yes indeed in videogames there is always a status switch, from that of the game to that of the menu or inventory
