### ISSUE TITLE
Let's make compile time shorter

### ISSUE THREAD

**Issue by CatCode79** [Davidster/ikari#7]
Ok, before jumping into the trace_full part I would like to improve the compilation times because they kill my Flow.

I need some information:
- Do you really need the crate dialoguer? I notice that it is used in only one place in a commented area. I think alternatively a simple environment variable could be used to pass run options.
- I notice that there are two crates that manage wavefront objs (obj_rs and wavefront_obj), do we really need both or can we do without one of them?
- What is the stb crate for? It seems to me to load an image and I wonder if you can use the crate image instead.
- Are there any actual advantages to using cgmath instead of nalgebra (which is already being used and compiled by rapier)?

**Comment by Davidster** [comment]
Dialoguer is definitely not needed, we could remove the commented code and take away the dependency. We could always check the git history to find the comment if we want to retrieve it in the future.

If in not mistaken there are some .obj files in the assets folder which we need the obj dependency(s) to load. But those could be converted to gltf in blender.

Stb is used to load the .hdr file format if in not mistaken, I'm not aware of a better alternative to load those, they weren't supported by the image crate last time I checked.

For cgmath, I felt more comfortable with their API than nalg, it seemed easier to work with for me. But it could be nice to try rewriting it all with nalg to see if it's actually more annoying to use. It would be great to have a single math library, there is currently some extra code in the project that is needed to convert between nalg and cgmath types.


Would be cool to try removing the unused crates (I'd start with dialoguer) and see empirically how much faster it is by measuring the compile times. Keep in mind that the dependencies only get recompiled occasionally, usually they get cached by cargo to subsequent compilations are significantly faster.

I think a more promising avenue for improving compile times would be to split the project up into multiple crates, so we can benefit from the cargo cache when we only changed 1 file and the crates in the project can compile in parallel if we changed many files across the project.

What do you think?

**Comment by CatCode79** [comment]
> Dialoguer is definitely not needed, we could remove the commented code and take away the dependency.

Perfect!

> If in not mistaken there are some .obj files in the assets folder which we need the obj dependency(s) to load. But those could be converted to gltf in blender.

Nice idea!
(I checked the gltf crate for one thing and found it hasn't been actively maintained since February :shock:)

> Stb is used to load the .hdr file format if in not mistaken, I'm not aware of a better alternative to load those, they weren't supported by the image crate last time I checked.

I checked the image crate cargo.toml and it seems they have implemented it, there is hdr feature. Would be great! Alternatively I discovered that we could activate the feature only for the images of the crate stb.

> For cgmath, I felt more comfortable with their API than nalg, it seemed easier to work with for me. But it could be nice to try rewriting it all with nalg to see if it's actually more annoying to use. It would be great to have a single math library, there is currently some extra code in the project that is needed to convert between nalg and cgmath types.

Yeah.. The math crates ecosystem is mature but, if one wants to make the best choice for his project, a non-trivial choice.
I open a discussion about it, it's a choice that is better to make when we have more code to understand what we want to do.

> Keep in mind that the dependencies only get recompiled occasionally, usually they get cached by cargo to subsequent compilations are significantly faster.

You're right, but sometimes it happens like the other day that between stable, nightly, debug, release I compiled quite a few times, on my pc it takes up to 8 minutes. Luckily it doesn't happen often, but I'm one of those who do a cargo update too often :D
I need to go over what bevy did to decrease compile times, they did a great job.

> I think a more promising avenue for improving compile times would be to split the project up into multiple crates, so we can benefit from the cargo cache when we only changed 1 file and the crates in the project can compile in parallel if we changed many files across the project.

I have developed a point of view that I find interesting on how to separate the code in crate to improve compilation times.

(you already know these things but I say them for completeness:) first of all it is not said that separating the code into various crates can improve compilation times, probably yes (especially if you have a cpu with many cores) but there is to bear in mind that however there is a greater overhead in the management of the dependency graph, in the choice of what to compile when, in the context switch between the various processes and finally, probably the most heavy thing of all, the linking.
What I've noticed is that typically there are already so many crates to compile that adding a not too many crates I don't think changes much.

But what I've noticed in many projects with some dependencies (using cargo build --timings) is that the build tends to separate into quite similar stages.
- phase one: in which many small crates are compiled and some fundamentals begin to be compiled, including syn
- phase two is a LONG wait for the whole crate syn to be compiled (in some projects here the cores are not used to their maximum because they only compile that and little else)
- stage three is when all the crates that were waiting for syn to compile can start compiling, the names are always the same: serde_derive, thiserror, bytemuck_derive among others (I call it: The Wall Of Syn)
- phase four are all the other crates that depend on the previous crates, naga's situation is particularly dramatic: without thiserror it cannot compile, and all the wgpu crates follow...
The rest are (generally) a few other crates (perhaps heavy because related to rendering, I'm thinking of the rend3 project) and finally the linking.
(sometimes I joke about it saying: The Sin of using Syn)

So one thing I've learned is that, if possible, separate the part that depends on the syn-crates, with respect to the rest of the code (it's something I sometimes notice in rust projects, a crate derives separate from the rest)

Basically, the separation of code in crate must be done more for a semantic separation. Any other sort of separation I think is not "idiomatic" for code design. I say this to point out that a separation of the code in crate to improve compile times, as I have developed, may not be ideal from a pure design point of view.

The idea is to separate the crates not so much into semantic units but into units of macro-dependencies.
So there is a crate that contains all the code that depends on wgpu, another one on winit, another one on rapier...
It is imperative that the crate that contains the winit-base code shouldn't have the wgpu dependency and the like.

Said like this, it seems easy, but sometimes making these crates talk to each other isn't fun... in general I solved it by reducing the messages to primitive types, in some cases however losing the semantics of the original type (this is because I didn't want, for now, to be a crate-types to be used to communicate between crates).

However I think that a compromise can be reached without having to go to such an extreme model, it works very well for me because it is for a personal project, in which only I work, so I don't need to give a descriptive api.

Sorry I wrote a wall of text, for now I'll simply try to make some improvements and then we'll think about what we'll have.

**Comment by Davidster** [comment]
Awesome! Thanks for all the details. I'll be on vacation this weekend but looking forward to giving it a closer read next week 😃

**Comment by CatCode79** [comment]
Regarding to Bevy there is this section which is helpful:
https://bevyengine.org/learn/book/getting-started/setup/#enable-fast-compiles-optional

> Is there anything in this project that depends on syn?

Our "Wall of Syn" is formed by:
- bytemuck_derive (used by image, nalgebra and wgpu-sandbox). Probably difficult to do without this dependency, better to isolate it inside a separate crate.
- serde_derive (used by gltf, obj-rs and puffin). I think it would be possible to make the gltf crate's use of serde optional, but given the unmaintained state of this latter crate there isn't much scope for that. A still embryonic alternative could be [this crate](https://github.com/expenses/goth-gltf) (which uses miniserde instead)
- thiserror-impl (used by naga, cpal, minimp3 and wgpu-hal). Probably one day I will open an issue of the naga repo asking to use anyhow instead of thiserror (a similar issue already exists actually)
- nalgebra-macros
- num-derive (used by rapier and parry).

Here is the situation after the Wall of Syn:
![wall_of_syn](https://user-images.githubusercontent.com/12321983/206426121-07ebaf86-4129-4b1b-948b-7f180a787683.png)

In the first analysis I would like to create two crates from the project: one for managing assets (gltf) and another for physics (nalgebra + rapier & Co). From a design point of view creating another crate for rendering would be natural, but from a compile point of view less so because bytemuck and thiserror are used in other contexts.

> Personally, the part that bothers me the most about the compile time is when all the deps are already cached but changing one line in the project causes a 10 second recompile. Is there a way to check what the build is doing for the 10 seconds? If it's the linker then I assume there's nothing we can do about it?

By any chance do you mean re-indexing? I use Intellij Idea and it's pretty boring, it does it randomly every now and then and blocks everything...
If so I think [this link](https://stackoverflow.com/questions/29965896/how-can-i-stop-indexing-intellij-idea) can help, I haven't tried it yet because every now and then I modify the code externally from the IDE and I would risk having desynchronized code.

**Comment by CatCode79** [comment]
> That bevy doc is great, would be interested in seeing how those things would affect this project, except that I don't know how to set up dynamic linking. I've never heard of that being done in rust before.

Neither do I. It seems to use [this crate](https://github.com/bevyengine/bevy/blob/main/crates/bevy_dylib/Cargo.toml) to enable dynamic linking, and then compile all the crates with bevy_internal. I vaguely remember having had problems with this type of compilation in bevy (maybe memory owerflow), probably because thanks to this type of compilation there weren't any more "barriers" to stop the use of all possible resources (and beyond) and my pc couldn't handle it :D

> Ok damn, no getting around that then. Splitting the crates by gltf and physics sounds fine to me. I have no problem with it off the top of my head. Feel free to try it out if it interests you 😃.

Cool! In the next few days, however, I will focus first on the new profiling system, so you can use it to see what happens with the gpu.

> Nope, I was just referring to the fact that running cargo run takes 10 seconds after changing one little line of code anywhere in the project.

Heck you're right, I thought it was all in all normal that he did it but looking better I discovered that among the additional (and removable) actions before run set by default in the intellij Idea there is the build. Maybe vscode does a similar thing too?

I think vscode is better than Intellij Idea, I use the latter for various reasons (some not as solid as they used to be). Maybe I'll change, but I'd like to wait to see how both IDEs will cope with the new graphical interface (I remember that they were working on very light and fast interfaces to load).

I discovered this super interesting article, I was very impressed by the section about ramdisk:
https://endler.dev/2020/rust-compile-times/#use-a-ramdisk-for-compilation
using windows I can't test it and I don't know when it can improve compile times, but the thing is tantalizing

**Comment by Davidster** [comment]
> Cool! In the next few days, however, I will focus first on the new profiling system, so you can use it to see what happens with the gpu.

Amazing! Very excited to see how that looks.

> Maybe vscode does a similar thing too?

True, I'm sure there's a way to set that up, should help me feel better about it.

Thanks for the link! There are so many good resources in this thread now for compiling faster, especially on linux with mold it seems great

**Comment by CatCode79** [comment]
Positive note: the compilation time in the release is 3 minutes (instead of 5 and a half minutes) on my pc, apparently in the release the Wall of Syn is not even formed, i.e. there is a bottleneck like "long tail", much more linear and natural

**Comment by Davidster** [comment]
nice! I'm glad to hear that

**Comment by CatCode79** [comment]
With [#32 PR](https://github.com/Davidster/ikari/pull/32) which halved the build times for the dev profile, I'd say we solved the problem and I'm closing the issue
