### ISSUE TITLE
Video on readme: mime problem

### ISSUE THREAD

**Issue by CatCode79** [Davidster/ikari#82]
Occasionally, but not always, I get an error from the example videos in the Readme file, here's what I get instead:
![mime_problem](https://github.com/Davidster/ikari/assets/12321983/59ab8e88-3f23-413e-9015-77a21e1369ff)

I'm using the latest version of Firefox on Windows 10, maybe converting them to WebM format is better?

**Comment by Davidster** [comment]
I wonder if this still happens?

**Comment by CatCode79** [comment]
It hasn't happened to me for months, I have no idea if it was the browser's fault, github or something else, but I think they fixed it
